"""Add featured table and fix gallery relationship

Revision ID: fc68988d6958
Revises: 9ccef05aff13
Create Date: 2026-06-20 10:12:32.927701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc68988d6958'
down_revision: Union[str, Sequence[str], None] = '9ccef05aff13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('price', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_featured_id'), 'featured', ['id'], unique=False)
    op.add_column('business_settings', sa.Column('business_logo', sa.String(length=255), nullable=True))
    op.add_column('business_settings', sa.Column('linkedin_url', sa.String(length=255), nullable=True))
    op.add_column('business_settings', sa.Column('x_url', sa.String(length=255), nullable=True))
    op.add_column('business_settings', sa.Column('youtube_url', sa.String(length=255), nullable=True))
    op.drop_column('homepage_content', 'description')
    op.drop_column('homepage_content', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('homepage_content', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('homepage_content', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('business_settings', 'youtube_url')
    op.drop_column('business_settings', 'x_url')
    op.drop_column('business_settings', 'linkedin_url')
    op.drop_column('business_settings', 'business_logo')
    op.drop_index(op.f('ix_featured_id'), table_name='featured')
    op.drop_table('featured')
    # ### end Alembic commands ###
